package kma.qlbh.interfaces.seller;

import java.util.ArrayList;
import javax.swing.JFrame;
import kma.qlbh.dao.FoodItemDao;
import kma.qlbh.models.FoodItem;
import kma.qlbh.utils.ErrorPopup;

public class Dashboard extends javax.swing.JFrame {

    ArrayList<FoodItem> foods = new ArrayList<>();
    FoodItemDao foodItemDao = new FoodItemDao();

    public Dashboard() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        initItems();
        panelContent.removeAll();
        foods.forEach(food -> {
            panelContent.add(new FoodPane(food));
        });
        panelContent.updateUI();
    }

    private void initItems() {
        try {
            foods = foodItemDao.getAll();
        } catch (Exception e) {
            ErrorPopup.show(e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTop = new javax.swing.JPanel();
        btnSelectTable = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        panelLeft = new javax.swing.JPanel();
        panelRight = new javax.swing.JPanel();
        panelPaging = new javax.swing.JPanel();
        panelContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1920, 1080));

        panelTop.setBackground(new java.awt.Color(204, 255, 0));
        panelTop.setPreferredSize(new java.awt.Dimension(1920, 60));

        btnSelectTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSelectTable.setText("Chọn Bàn");
        btnSelectTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSelectTable.setFocusPainted(false);
        btnSelectTable.setHideActionText(true);
        btnSelectTable.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSelectTable.setIconTextGap(5);
        btnSelectTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectTableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTopLayout = new javax.swing.GroupLayout(panelTop);
        panelTop.setLayout(panelTopLayout);
        panelTopLayout.setHorizontalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTopLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(btnSelectTable)
                .addContainerGap(1788, Short.MAX_VALUE))
        );
        panelTopLayout.setVerticalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTopLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnSelectTable)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(panelTop, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setRequestFocusEnabled(false);
        jPanel2.setLayout(new java.awt.BorderLayout());

        panelLeft.setBackground(new java.awt.Color(153, 0, 255));
        panelLeft.setPreferredSize(new java.awt.Dimension(640, 1020));

        javax.swing.GroupLayout panelLeftLayout = new javax.swing.GroupLayout(panelLeft);
        panelLeft.setLayout(panelLeftLayout);
        panelLeftLayout.setHorizontalGroup(
            panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1920, Short.MAX_VALUE)
        );
        panelLeftLayout.setVerticalGroup(
            panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );

        jPanel2.add(panelLeft, java.awt.BorderLayout.PAGE_START);

        panelRight.setBackground(new java.awt.Color(204, 102, 255));
        panelRight.setLayout(new java.awt.BorderLayout());

        panelPaging.setPreferredSize(new java.awt.Dimension(1280, 60));

        javax.swing.GroupLayout panelPagingLayout = new javax.swing.GroupLayout(panelPaging);
        panelPaging.setLayout(panelPagingLayout);
        panelPagingLayout.setHorizontalGroup(
            panelPagingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1920, Short.MAX_VALUE)
        );
        panelPagingLayout.setVerticalGroup(
            panelPagingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        panelRight.add(panelPaging, java.awt.BorderLayout.PAGE_END);

        panelContent.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        panelContent.setOpaque(false);
        panelContent.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));
        panelRight.add(panelContent, java.awt.BorderLayout.CENTER);

        jPanel2.add(panelRight, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectTableActionPerformed

    }//GEN-LAST:event_btnSelectTableActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel("com.formdev.flatlaf.FlatLightLaf");
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSelectTable;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelContent;
    private javax.swing.JPanel panelLeft;
    private javax.swing.JPanel panelPaging;
    private javax.swing.JPanel panelRight;
    private javax.swing.JPanel panelTop;
    // End of variables declaration//GEN-END:variables
}
