/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kma.qlbh.interfaces.admin.table;

import java.util.ArrayList;
import kma.qlbh.dao.TableDao;
import kma.qlbh.models.Table;

/**
 *
 * @author MSI
 */

public class PnlTableMenu extends javax.swing.JPanel {

    /**
     * Creates new form PnlTableMenu
     */
    TableDao tableDao = new TableDao();
    public PnlTableMenu() {
        initComponents();
        try {
            ArrayList<Table> Tables = tableDao.getAll();
            for(Table table : Tables){
                this.add(new PnlTable(table.getId(), TOOL_TIP_TEXT_KEY, TOOL_TIP_TEXT_KEY, TOOL_TIP_TEXT_KEY));
            }
        } catch (Exception e) {
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 4, true));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
