package kma.qlbh.interfaces.components;

import java.awt.event.MouseAdapter;

/**
 *
 * @author Tran Duc Cuong<clonebmn2itt@gmail.com>
 */
public class PnlFoodItem extends javax.swing.JPanel {

    /**
     * Creates new form pnlFoodItem
     */
    MouseAdapter onClick;

    public PnlFoodItem() {
        initComponents();
    }

    public PnlFoodItem(String name, String urlImage, long price, MouseAdapter onClick) {
        initComponents();
        this.onClick = onClick;
        initEvents();
        labelName.setText(name);
    }

    private void initEvents() {
        labelImage.addMouseListener(this.onClick);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelImage = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 255, 0));

        labelImage.setBackground(new java.awt.Color(51, 255, 0));
        labelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kma/qlbh/resources/chicken_rice.png"))); // NOI18N
        labelImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelName.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(labelName))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(25, Short.MAX_VALUE)
                        .addComponent(labelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(labelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelName))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelImage;
    private javax.swing.JLabel labelName;
    // End of variables declaration//GEN-END:variables
}
